### PR TITLE
Update cloudflare.yaml

### PR DESCRIPTION
**Pull request by eseidel**
Quote from Cloudflare just now:

"If SSO is the only goal, we can accomplish this via an Enterprise-Minus contract, which comes in at $12k/yr."

### CODE REVIEW

**Comment by MMore** [comment]
Thanks for the quick update @eseidel!!

**Comment by eseidel** [comment]
Someone from Cloudflare claims they're going to fix this. :shrug: https://x.com/NitinBRao/status/1833941049586446630

**Comment by eseidel** [comment]
https://blog.cloudflare.com/a-safer-internet-with-cloudflare 🎉

**Comment by MMore** [comment]
Nice, at least Google. But still no general SSO though according to their pricing page. Soon maybe 🤞

**Pull request merged**
